---
module:
  hugoVersion:
    extended: false
    min: "0.79.0"
  mounts:
  - source: assets
    target: assets
  - source: layouts/partials
    target: layouts/partials
  - source: layouts/shortcodes
    target: layouts/shortcodes