---
module:
  hugoVersion:
    extended: false
    min: "0.79.0"
  mounts:
  - source: assets/monetization.js
    target: assets/monetization.js
  - source: layouts/partials/monetization.html
    target: layouts/partials/monetization.html
  - source: layouts/shortcodes/monetization.html
    target: layouts/shortcodes/monetization.html